
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: //:distribution

from setuptools import setup

setup(**{
    'author': 'Frontrunner',
    'author_email': 'support@getfrontrunner.com',
    'classifiers': [
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: Apache Software License',
        'Natural Language :: English',
        'Topic :: Games/Entertainment',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
    ],
    'description': 'Frontrunner SDK',
    'entry_points': {
        'console_scripts': [
            '_fake = frontrunner_sdk:_fake',
        ],
    },
    'install_requires': (
        'aiohttp~=3.8.4',
        'certifi>=14.05.14',
        'grpcio',
        'injective-py==0.6.*',
        'protobuf==3.*',
        'python_dateutil>=2.5.3',
        'six>=1.10',
        'urllib3>=1.15.1',
    ),
    'license': 'Apache-2.0',
    'name': 'frontrunner-sdk',
    'namespace_packages': (
    ),
    'package_data': {
    },
    'packages': (
        'frontrunner_sdk',
        'frontrunner_sdk.clients',
        'frontrunner_sdk.commands',
        'frontrunner_sdk.commands.frontrunner',
        'frontrunner_sdk.commands.injective',
        'frontrunner_sdk.config',
        'frontrunner_sdk.exceptions',
        'frontrunner_sdk.facades',
        'frontrunner_sdk.helpers',
        'frontrunner_sdk.logging',
        'frontrunner_sdk.models',
        'frontrunner_sdk.openapi.frontrunner_api',
        'frontrunner_sdk.openapi.frontrunner_api.api',
        'frontrunner_sdk.openapi.frontrunner_api.models',
    ),
    'python_requires': '>=3.8,<4',
    'url': 'https://github.com/GetFrontrunner/frontrunner-sdk',
    'version': '0.1.0',
})
