# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/api/attr.base.ipynb.

# %% auto 0
__all__ = ['Attribution']

# %% ../../nbs/api/attr.base.ipynb 3
from ..imports import *

# %% ../../nbs/api/attr.base.ipynb 4
class Attribution:
    def __init__(
        self,
        func: Callable, # A black-box function to be explained
        additional_func_args: Dict = None, # Additional arguments for the black-box function
    ): 
        self.func = func
        self.additional_func_args = additional_func_args

    def attribute(self, inputs: jnp.ndarray, **kwargs) -> jnp.ndarray:
        """Compute attribution for a given input"""
        raise NotImplementedError
