
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-27T15:01:09-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "9289b00c46ac19f09b317fcb9f943189ba3f1892",
 "version": "0.1.2.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
