
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import java.util.function
import org.optaplanner.core.config
import typing



class ConstructionHeuristicForagerConfig(org.optaplanner.core.config.AbstractConfig['ConstructionHeuristicForagerConfig']):
    def __init__(self): ...
    def copyConfig(self) -> 'ConstructionHeuristicForagerConfig': ...
    def getPickEarlyType(self) -> 'ConstructionHeuristicPickEarlyType': ...
    def inherit(self, constructionHeuristicForagerConfig: 'ConstructionHeuristicForagerConfig') -> 'ConstructionHeuristicForagerConfig': ...
    def setPickEarlyType(self, constructionHeuristicPickEarlyType: 'ConstructionHeuristicPickEarlyType') -> None: ...
    def visitReferencedClasses(self, consumer: typing.Union[java.util.function.Consumer[typing.Type[typing.Any]], typing.Callable[[typing.Type[typing.Any]], None]]) -> None: ...
    def withPickEarlyType(self, constructionHeuristicPickEarlyType: 'ConstructionHeuristicPickEarlyType') -> 'ConstructionHeuristicForagerConfig': ...

class ConstructionHeuristicPickEarlyType(java.lang.Enum['ConstructionHeuristicPickEarlyType']):
    NEVER: typing.ClassVar['ConstructionHeuristicPickEarlyType'] = ...
    FIRST_NON_DETERIORATING_SCORE: typing.ClassVar['ConstructionHeuristicPickEarlyType'] = ...
    FIRST_FEASIBLE_SCORE: typing.ClassVar['ConstructionHeuristicPickEarlyType'] = ...
    FIRST_FEASIBLE_SCORE_OR_NON_DETERIORATING_HARD: typing.ClassVar['ConstructionHeuristicPickEarlyType'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: str) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: str) -> 'ConstructionHeuristicPickEarlyType': ...
    @staticmethod
    def values() -> typing.MutableSequence['ConstructionHeuristicPickEarlyType']: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("org.optaplanner.core.config.constructionheuristic.decider.forager")``.

    ConstructionHeuristicForagerConfig: typing.Type[ConstructionHeuristicForagerConfig]
    ConstructionHeuristicPickEarlyType: typing.Type[ConstructionHeuristicPickEarlyType]
