
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-25T18:25:35-0400",
 "dirty": true,
 "error": null,
 "full-revisionid": "8db0ceb01f48d23051082b4aff40b98a5108fb0f",
 "version": "2.11.1b3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
