#ifndef MYPYC_NATIVE_INTERNAL_dd3465df282eef100818_H
#define MYPYC_NATIVE_INTERNAL_dd3465df282eef100818_H
#include <Python.h>
#include <CPy.h>
#include "__native_dd3465df282eef100818.h"

int CPyGlobalsInit(void);

extern PyObject *CPyStatics[106];
extern const char * const CPyLit_Str[];
extern const char * const CPyLit_Bytes[];
extern const char * const CPyLit_Int[];
extern const double CPyLit_Float[];
extern const double CPyLit_Complex[];
extern const int CPyLit_Tuple[];
extern const int CPyLit_FrozenSet[];
extern CPyModule *CPyModule_asgi_context___headers_extrator_internal;
extern CPyModule *CPyModule_asgi_context___headers_extrator;
extern PyObject *CPyStatic_headers_extrator___globals;
extern CPyModule *CPyModule_builtins_internal;
extern CPyModule *CPyModule_builtins;
extern CPyModule *CPyModule_json_internal;
extern CPyModule *CPyModule_json;
extern CPyModule *CPyModule_abc_internal;
extern CPyModule *CPyModule_abc;
extern CPyModule *CPyModule_collections___abc_internal;
extern CPyModule *CPyModule_collections___abc;
extern CPyModule *CPyModule_dataclasses_internal;
extern CPyModule *CPyModule_dataclasses;
extern CPyModule *CPyModule_functools_internal;
extern CPyModule *CPyModule_functools;
extern CPyModule *CPyModule_http_internal;
extern CPyModule *CPyModule_http;
extern CPyModule *CPyModule_typing_internal;
extern CPyModule *CPyModule_typing;
extern CPyModule *CPyModule_mypy_extensions_internal;
extern CPyModule *CPyModule_mypy_extensions;
extern CPyModule *CPyModule_asgi_context___context_internal;
extern CPyModule *CPyModule_asgi_context___context;
extern CPyModule *CPyModule_asgi_context___protocol_internal;
extern CPyModule *CPyModule_asgi_context___protocol;
extern PyObject *CPyStatic_protocol___globals;
extern PyObject *CPyStatic_context___globals;
extern CPyModule *CPyModule_collections_internal;
extern CPyModule *CPyModule_collections;
extern CPyModule *CPyModule_contextlib_internal;
extern CPyModule *CPyModule_contextlib;
extern CPyModule *CPyModule_contextvars_internal;
extern CPyModule *CPyModule_contextvars;
extern CPyModule *CPyModule_asgi_context_internal;
extern CPyModule *CPyModule_asgi_context;
extern PyObject *CPyStatic_asgi_context___globals;
extern PyObject *CPyStatic_headers_extrator___asgi_context___headers_extrator___HeadersExtractorMiddlewareFactory___build___validation_config;
extern PyTypeObject *CPyType_headers_extrator___ValidationConfig;
extern PyObject *CPyDef_headers_extrator___ValidationConfig(PyObject *cpy_r_args, PyObject *cpy_r_kwargs);
extern PyTypeObject *CPyType_headers_extrator___AbstractHeadersExtractorMiddleware;
extern PyObject *CPyDef_headers_extrator___AbstractHeadersExtractorMiddleware(PyObject *cpy_r_app);
extern PyTypeObject *CPyType_headers_extrator___HeadersExtractorMiddlewareFactory;
extern PyObject *CPyDef_headers_extrator___HeadersExtractorMiddlewareFactory(void);
extern PyTypeObject *CPyType_headers_extrator_____call___3_AbstractHeadersExtractorMiddleware_env;
extern PyObject *CPyDef_headers_extrator_____call___3_AbstractHeadersExtractorMiddleware_env(void);
extern PyTypeObject *CPyType_headers_extrator_____call___3_AbstractHeadersExtractorMiddleware_gen;
extern PyObject *CPyDef_headers_extrator_____call___3_AbstractHeadersExtractorMiddleware_gen(void);
extern PyTypeObject *CPyType_headers_extrator___send_response_AbstractHeadersExtractorMiddleware_env;
extern PyObject *CPyDef_headers_extrator___send_response_AbstractHeadersExtractorMiddleware_env(void);
extern PyTypeObject *CPyType_headers_extrator___send_response_AbstractHeadersExtractorMiddleware_gen;
extern PyObject *CPyDef_headers_extrator___send_response_AbstractHeadersExtractorMiddleware_gen(void);
extern PyTypeObject *CPyType_headers_extrator___build_HeadersExtractorMiddlewareFactory_env;
extern PyObject *CPyDef_headers_extrator___build_HeadersExtractorMiddlewareFactory_env(void);
extern PyTypeObject *CPyType_headers_extrator_____mypyc_lambda__0_build_HeadersExtractorMiddlewareFactory_obj;
extern PyObject *CPyDef_headers_extrator_____mypyc_lambda__0_build_HeadersExtractorMiddlewareFactory_obj(void);
extern PyTypeObject *CPyType_headers_extrator_____mypyc_lambda__1_build_HeadersExtractorMiddlewareFactory_obj;
extern PyObject *CPyDef_headers_extrator_____mypyc_lambda__1_build_HeadersExtractorMiddlewareFactory_obj(void);
extern char CPyDef_headers_extrator___AbstractHeadersExtractorMiddleware_____init__(PyObject *cpy_r_self, PyObject *cpy_r_app);
extern PyObject *CPyPy_headers_extrator___AbstractHeadersExtractorMiddleware_____init__(PyObject *self, PyObject *args, PyObject *kw);
extern char CPyDef_headers_extrator___AbstractHeadersExtractorMiddleware_____init___3__AbstractHeadersExtractorMiddleware_glue(PyObject *cpy_r_self, PyObject *cpy_r_app);
extern PyObject *CPyPy_headers_extrator___AbstractHeadersExtractorMiddleware_____init___3__AbstractHeadersExtractorMiddleware_glue(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator___AbstractHeadersExtractorMiddleware___header_names(PyObject *cpy_r_self);
extern PyObject *CPyPy_headers_extrator___AbstractHeadersExtractorMiddleware___header_names(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator___AbstractHeadersExtractorMiddleware___header_names__AbstractHeadersExtractorMiddleware_glue(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy_headers_extrator___AbstractHeadersExtractorMiddleware___header_names__AbstractHeadersExtractorMiddleware_glue(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator___AbstractHeadersExtractorMiddleware___validation_config(PyObject *cpy_r_self);
extern PyObject *CPyPy_headers_extrator___AbstractHeadersExtractorMiddleware___validation_config(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator___AbstractHeadersExtractorMiddleware___validation_config__AbstractHeadersExtractorMiddleware_glue(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy_headers_extrator___AbstractHeadersExtractorMiddleware___validation_config__AbstractHeadersExtractorMiddleware_glue(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator_____call___3_AbstractHeadersExtractorMiddleware_gen_____mypyc_generator_helper__(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_type, PyObject *cpy_r_value, PyObject *cpy_r_traceback, PyObject *cpy_r_arg);
extern PyObject *CPyPy_headers_extrator_____call___3_AbstractHeadersExtractorMiddleware_gen_____mypyc_generator_helper__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator_____call___3_AbstractHeadersExtractorMiddleware_gen_____next__(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy_headers_extrator_____call___3_AbstractHeadersExtractorMiddleware_gen_____next__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator_____call___3_AbstractHeadersExtractorMiddleware_gen___send(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_arg);
extern PyObject *CPyPy_headers_extrator_____call___3_AbstractHeadersExtractorMiddleware_gen___send(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator_____call___3_AbstractHeadersExtractorMiddleware_gen_____iter__(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy_headers_extrator_____call___3_AbstractHeadersExtractorMiddleware_gen_____iter__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator_____call___3_AbstractHeadersExtractorMiddleware_gen___throw(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_type, PyObject *cpy_r_value, PyObject *cpy_r_traceback);
extern PyObject *CPyPy_headers_extrator_____call___3_AbstractHeadersExtractorMiddleware_gen___throw(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator_____call___3_AbstractHeadersExtractorMiddleware_gen___close(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy_headers_extrator_____call___3_AbstractHeadersExtractorMiddleware_gen___close(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator_____call___3_AbstractHeadersExtractorMiddleware_gen_____await__(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy_headers_extrator_____call___3_AbstractHeadersExtractorMiddleware_gen_____await__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator___AbstractHeadersExtractorMiddleware_____call__(PyObject *cpy_r_self, PyObject *cpy_r_scope, PyObject *cpy_r_receive, PyObject *cpy_r_send);
extern PyObject *CPyPy_headers_extrator___AbstractHeadersExtractorMiddleware_____call__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator___AbstractHeadersExtractorMiddleware_____call___3__AbstractHeadersExtractorMiddleware_glue(PyObject *cpy_r_self, PyObject *cpy_r_scope, PyObject *cpy_r_receive, PyObject *cpy_r_send);
extern PyObject *CPyPy_headers_extrator___AbstractHeadersExtractorMiddleware_____call___3__AbstractHeadersExtractorMiddleware_glue(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator___send_response_AbstractHeadersExtractorMiddleware_gen_____mypyc_generator_helper__(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_type, PyObject *cpy_r_value, PyObject *cpy_r_traceback, PyObject *cpy_r_arg);
extern PyObject *CPyPy_headers_extrator___send_response_AbstractHeadersExtractorMiddleware_gen_____mypyc_generator_helper__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator___send_response_AbstractHeadersExtractorMiddleware_gen_____next__(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy_headers_extrator___send_response_AbstractHeadersExtractorMiddleware_gen_____next__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator___send_response_AbstractHeadersExtractorMiddleware_gen___send(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_arg);
extern PyObject *CPyPy_headers_extrator___send_response_AbstractHeadersExtractorMiddleware_gen___send(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator___send_response_AbstractHeadersExtractorMiddleware_gen_____iter__(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy_headers_extrator___send_response_AbstractHeadersExtractorMiddleware_gen_____iter__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator___send_response_AbstractHeadersExtractorMiddleware_gen___throw(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_type, PyObject *cpy_r_value, PyObject *cpy_r_traceback);
extern PyObject *CPyPy_headers_extrator___send_response_AbstractHeadersExtractorMiddleware_gen___throw(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator___send_response_AbstractHeadersExtractorMiddleware_gen___close(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy_headers_extrator___send_response_AbstractHeadersExtractorMiddleware_gen___close(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator___send_response_AbstractHeadersExtractorMiddleware_gen_____await__(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy_headers_extrator___send_response_AbstractHeadersExtractorMiddleware_gen_____await__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator___AbstractHeadersExtractorMiddleware___send_response(PyObject *cpy_r_send, PyObject *cpy_r_status, PyObject *cpy_r_details);
extern PyObject *CPyPy_headers_extrator___AbstractHeadersExtractorMiddleware___send_response(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator___AbstractHeadersExtractorMiddleware___send_response__AbstractHeadersExtractorMiddleware_glue(PyObject *cpy_r_send, PyObject *cpy_r_status, PyObject *cpy_r_details);
extern PyObject *CPyPy_headers_extrator___AbstractHeadersExtractorMiddleware___send_response__AbstractHeadersExtractorMiddleware_glue(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator_____mypyc_lambda__0_build_HeadersExtractorMiddlewareFactory_obj_____get__(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_instance, PyObject *cpy_r_owner);
extern PyObject *CPyPy_headers_extrator_____mypyc_lambda__0_build_HeadersExtractorMiddlewareFactory_obj_____get__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator_____mypyc_lambda__0_build_HeadersExtractorMiddlewareFactory_obj_____call__(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_self);
extern PyObject *CPyPy_headers_extrator_____mypyc_lambda__0_build_HeadersExtractorMiddlewareFactory_obj_____call__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator_____mypyc_lambda__1_build_HeadersExtractorMiddlewareFactory_obj_____get__(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_instance, PyObject *cpy_r_owner);
extern PyObject *CPyPy_headers_extrator_____mypyc_lambda__1_build_HeadersExtractorMiddlewareFactory_obj_____get__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator_____mypyc_lambda__1_build_HeadersExtractorMiddlewareFactory_obj_____call__(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_self);
extern PyObject *CPyPy_headers_extrator_____mypyc_lambda__1_build_HeadersExtractorMiddlewareFactory_obj_____call__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator___HeadersExtractorMiddlewareFactory___build(PyObject *cpy_r_base_name, PyObject *cpy_r_header_names, PyObject *cpy_r_validation_config);
extern PyObject *CPyPy_headers_extrator___HeadersExtractorMiddlewareFactory___build(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_headers_extrator___HeadersExtractorMiddlewareFactory____build_name(PyObject *cpy_r_base_name);
extern PyObject *CPyPy_headers_extrator___HeadersExtractorMiddlewareFactory____build_name(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern char CPyDef_headers_extrator_____top_level__(void);
extern char CPyDef_protocol_____top_level__(void);
extern PyTypeObject *CPyType_context___RequestContextException;
extern PyTypeObject *CPyType_context___Context;
extern PyObject *CPyDef_context___Context(void);
extern PyTypeObject *CPyType_context___ContextMiddleware;
extern PyObject *CPyDef_context___ContextMiddleware(PyObject *cpy_r_app);
extern PyTypeObject *CPyType_context___new_context_env;
extern PyObject *CPyDef_context___new_context_env(void);
extern PyTypeObject *CPyType_context___new_context_gen;
extern PyObject *CPyDef_context___new_context_gen(void);
extern PyTypeObject *CPyType_context_____call___3_ContextMiddleware_env;
extern PyObject *CPyDef_context_____call___3_ContextMiddleware_env(void);
extern PyTypeObject *CPyType_context_____call___3_ContextMiddleware_gen;
extern PyObject *CPyDef_context_____call___3_ContextMiddleware_gen(void);
extern char CPyDef_context___Context_____init__(PyObject *cpy_r_self);
extern PyObject *CPyPy_context___Context_____init__(PyObject *self, PyObject *args, PyObject *kw);
extern PyObject *CPyDef_context___Context___data(PyObject *cpy_r_self);
extern PyObject *CPyPy_context___Context___data(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_context___new_context_gen_____mypyc_generator_helper__(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_type, PyObject *cpy_r_value, PyObject *cpy_r_traceback, PyObject *cpy_r_arg);
extern PyObject *CPyPy_context___new_context_gen_____mypyc_generator_helper__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_context___new_context_gen_____next__(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy_context___new_context_gen_____next__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_context___new_context_gen___send(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_arg);
extern PyObject *CPyPy_context___new_context_gen___send(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_context___new_context_gen_____iter__(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy_context___new_context_gen_____iter__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_context___new_context_gen___throw(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_type, PyObject *cpy_r_value, PyObject *cpy_r_traceback);
extern PyObject *CPyPy_context___new_context_gen___throw(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_context___new_context_gen___close(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy_context___new_context_gen___close(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_context___new_context(void);
extern PyObject *CPyPy_context___new_context(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern char CPyDef_context___ContextMiddleware_____init__(PyObject *cpy_r_self, PyObject *cpy_r_app);
extern PyObject *CPyPy_context___ContextMiddleware_____init__(PyObject *self, PyObject *args, PyObject *kw);
extern PyObject *CPyDef_context_____call___3_ContextMiddleware_gen_____mypyc_generator_helper__(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_type, PyObject *cpy_r_value, PyObject *cpy_r_traceback, PyObject *cpy_r_arg);
extern PyObject *CPyPy_context_____call___3_ContextMiddleware_gen_____mypyc_generator_helper__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_context_____call___3_ContextMiddleware_gen_____next__(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy_context_____call___3_ContextMiddleware_gen_____next__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_context_____call___3_ContextMiddleware_gen___send(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_arg);
extern PyObject *CPyPy_context_____call___3_ContextMiddleware_gen___send(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_context_____call___3_ContextMiddleware_gen_____iter__(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy_context_____call___3_ContextMiddleware_gen_____iter__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_context_____call___3_ContextMiddleware_gen___throw(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_type, PyObject *cpy_r_value, PyObject *cpy_r_traceback);
extern PyObject *CPyPy_context_____call___3_ContextMiddleware_gen___throw(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_context_____call___3_ContextMiddleware_gen___close(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy_context_____call___3_ContextMiddleware_gen___close(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_context_____call___3_ContextMiddleware_gen_____await__(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy_context_____call___3_ContextMiddleware_gen_____await__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_context___ContextMiddleware_____call__(PyObject *cpy_r_self, PyObject *cpy_r_scope, PyObject *cpy_r_receive, PyObject *cpy_r_send);
extern PyObject *CPyPy_context___ContextMiddleware_____call__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern char CPyDef_context_____top_level__(void);
extern char CPyDef_asgi_context_____top_level__(void);
#endif
