# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flexlogger/automation/proto/TestSpecificationDocument.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;flexlogger/automation/proto/TestSpecificationDocument.proto\x12\x35national_instruments.flex_logger.automation.protocols2\x1b\n\x19TestSpecificationDocumentb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flexlogger.automation.proto.TestSpecificationDocument_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TESTSPECIFICATIONDOCUMENT._serialized_start=118
  _TESTSPECIFICATIONDOCUMENT._serialized_end=145
# @@protoc_insertion_point(module_scope)
