
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-27T15:52:50+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ccdedf78cc1ec64e377b1fb90c832652e790592",
 "version": "2.9.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
