
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-26T16:09:42-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "3eb2219663e5d4a39362c42a23087ad67b65e7bb",
 "version": "v0.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
