
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-28T08:41:22-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1921c7ee8613d1a84d062a893da99fffbc478897",
 "version": "0.0.164"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
