
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-25T18:14:36-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "db6158f3cf4aca4982454c5b73186536633465ae",
 "version": "v0.3.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
