
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-26T16:56:04-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "087cd80fb933baa6736368cb6d00e0883d26a632",
 "version": "v0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
