
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import org.kie.api.runtime.rule
import org.optaplanner.core.api.score
import org.optaplanner.core.api.score.holder
import typing



class HardSoftLongScore(org.optaplanner.core.api.score.Score['HardSoftLongScore']):
    ZERO: typing.ClassVar['HardSoftLongScore'] = ...
    ONE_HARD: typing.ClassVar['HardSoftLongScore'] = ...
    ONE_SOFT: typing.ClassVar['HardSoftLongScore'] = ...
    def abs(self) -> 'HardSoftLongScore': ...
    def add(self, hardSoftLongScore: 'HardSoftLongScore') -> 'HardSoftLongScore': ...
    def compareTo(self, hardSoftLongScore: 'HardSoftLongScore') -> int: ...
    def divide(self, double: float) -> 'HardSoftLongScore': ...
    def equals(self, object: typing.Any) -> bool: ...
    def getHardScore(self) -> int: ...
    def getSoftScore(self) -> int: ...
    def hardScore(self) -> int: ...
    def hashCode(self) -> int: ...
    def initScore(self) -> int: ...
    def isFeasible(self) -> bool: ...
    def multiply(self, double: float) -> 'HardSoftLongScore': ...
    @staticmethod
    def of(long: int, long2: int) -> 'HardSoftLongScore': ...
    @staticmethod
    def ofHard(long: int) -> 'HardSoftLongScore': ...
    @staticmethod
    def ofSoft(long: int) -> 'HardSoftLongScore': ...
    @staticmethod
    def ofUninitialized(int: int, long: int, long2: int) -> 'HardSoftLongScore': ...
    @staticmethod
    def parseScore(string: str) -> 'HardSoftLongScore': ...
    def power(self, double: float) -> 'HardSoftLongScore': ...
    def softScore(self) -> int: ...
    def subtract(self, hardSoftLongScore: 'HardSoftLongScore') -> 'HardSoftLongScore': ...
    def toLevelNumbers(self) -> typing.MutableSequence[java.lang.Number]: ...
    def toShortString(self) -> str: ...
    def toString(self) -> str: ...
    def withInitScore(self, int: int) -> 'HardSoftLongScore': ...
    def zero(self) -> 'HardSoftLongScore': ...

class HardSoftLongScoreHolder(org.optaplanner.core.api.score.holder.ScoreHolder[HardSoftLongScore]):
    def addHardConstraintMatch(self, ruleContext: org.kie.api.runtime.rule.RuleContext, long: int) -> None: ...
    def addMultiConstraintMatch(self, ruleContext: org.kie.api.runtime.rule.RuleContext, long: int, long2: int) -> None: ...
    def addSoftConstraintMatch(self, ruleContext: org.kie.api.runtime.rule.RuleContext, long: int) -> None: ...
    def impactScore(self, ruleContext: org.kie.api.runtime.rule.RuleContext, long: int) -> None: ...
    @typing.overload
    def penalize(self, ruleContext: org.kie.api.runtime.rule.RuleContext, long: int) -> None: ...
    @typing.overload
    def penalize(self, ruleContext: org.kie.api.runtime.rule.RuleContext, long: int, long2: int) -> None: ...
    @typing.overload
    def penalize(self, ruleContext: org.kie.api.runtime.rule.RuleContext) -> None: ...
    @typing.overload
    def reward(self, ruleContext: org.kie.api.runtime.rule.RuleContext, long: int) -> None: ...
    @typing.overload
    def reward(self, ruleContext: org.kie.api.runtime.rule.RuleContext, long: int, long2: int) -> None: ...
    @typing.overload
    def reward(self, ruleContext: org.kie.api.runtime.rule.RuleContext) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("org.optaplanner.core.api.score.buildin.hardsoftlong")``.

    HardSoftLongScore: typing.Type[HardSoftLongScore]
    HardSoftLongScoreHolder: typing.Type[HardSoftLongScoreHolder]
