# Generated by Django 3.2 on 2023-02-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_log_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='ip_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
