# Generated by Django 3.2 on 2023-02-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_log_priv_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='hashed',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
