
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import typing



class ScoreDefinitionType(java.lang.Enum['ScoreDefinitionType']):
    SIMPLE: typing.ClassVar['ScoreDefinitionType'] = ...
    SIMPLE_LONG: typing.ClassVar['ScoreDefinitionType'] = ...
    SIMPLE_DOUBLE: typing.ClassVar['ScoreDefinitionType'] = ...
    SIMPLE_BIG_DECIMAL: typing.ClassVar['ScoreDefinitionType'] = ...
    HARD_SOFT: typing.ClassVar['ScoreDefinitionType'] = ...
    HARD_SOFT_LONG: typing.ClassVar['ScoreDefinitionType'] = ...
    HARD_SOFT_DOUBLE: typing.ClassVar['ScoreDefinitionType'] = ...
    HARD_SOFT_BIG_DECIMAL: typing.ClassVar['ScoreDefinitionType'] = ...
    HARD_MEDIUM_SOFT: typing.ClassVar['ScoreDefinitionType'] = ...
    HARD_MEDIUM_SOFT_LONG: typing.ClassVar['ScoreDefinitionType'] = ...
    BENDABLE: typing.ClassVar['ScoreDefinitionType'] = ...
    BENDABLE_LONG: typing.ClassVar['ScoreDefinitionType'] = ...
    BENDABLE_BIG_DECIMAL: typing.ClassVar['ScoreDefinitionType'] = ...
    _valueOf_0__T = typing.TypeVar('_valueOf_0__T', bound=java.lang.Enum)  # <T>
    @typing.overload
    @staticmethod
    def valueOf(class_: typing.Type[_valueOf_0__T], string: str) -> _valueOf_0__T: ...
    @typing.overload
    @staticmethod
    def valueOf(string: str) -> 'ScoreDefinitionType': ...
    @staticmethod
    def values() -> typing.MutableSequence['ScoreDefinitionType']: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("org.optaplanner.core.config.score.definition")``.

    ScoreDefinitionType: typing.Type[ScoreDefinitionType]
