# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['scc_pyteam',
 'scc_pyteam.cookiecutter_templates',
 'scc_pyteam.cookiecutter_templates.django_template',
 'scc_pyteam.cookiecutter_templates.django_template.{{cookiecutter.project_name}}',
 'scc_pyteam.cookiecutter_templates.django_template.{{cookiecutter.project_name}}.configs',
 'scc_pyteam.cookiecutter_templates.django_template.{{cookiecutter.project_name}}.src',
 'scc_pyteam.cookiecutter_templates.django_template.{{cookiecutter.project_name}}.src.apps',
 'scc_pyteam.cookiecutter_templates.django_template.{{cookiecutter.project_name}}.src.apps.example',
 'scc_pyteam.cookiecutter_templates.django_template.{{cookiecutter.project_name}}.src.apps.example.admin',
 'scc_pyteam.cookiecutter_templates.django_template.{{cookiecutter.project_name}}.src.apps.example.api',
 'scc_pyteam.cookiecutter_templates.django_template.{{cookiecutter.project_name}}.src.apps.example.api.schemas',
 'scc_pyteam.cookiecutter_templates.django_template.{{cookiecutter.project_name}}.src.apps.example.api.utils',
 'scc_pyteam.cookiecutter_templates.django_template.{{cookiecutter.project_name}}.src.apps.example.migrations',
 'scc_pyteam.cookiecutter_templates.django_template.{{cookiecutter.project_name}}.src.apps.example.models',
 'scc_pyteam.cookiecutter_templates.django_template.{{cookiecutter.project_name}}.src.apps.example.serializers',
 'scc_pyteam.cookiecutter_templates.django_template.{{cookiecutter.project_name}}.src.apps.example.views',
 'scc_pyteam.cookiecutter_templates.django_template.{{cookiecutter.project_name}}.src.constants',
 'scc_pyteam.cookiecutter_templates.django_template.{{cookiecutter.project_name}}.src.project',
 'scc_pyteam.cookiecutter_templates.django_template.{{cookiecutter.project_name}}.src.project.templates',
 'scc_pyteam.cookiecutter_templates.django_template.{{cookiecutter.project_name}}.src.schema',
 'scc_pyteam.cookiecutter_templates.django_template.{{cookiecutter.project_name}}.tests',
 'scc_pyteam.cookiecutter_templates.fastapi_template',
 'scc_pyteam.cookiecutter_templates.fastapi_template.{{cookiecutter.project_name}}',
 'scc_pyteam.cookiecutter_templates.fastapi_template.{{cookiecutter.project_name}}.configs',
 'scc_pyteam.cookiecutter_templates.fastapi_template.{{cookiecutter.project_name}}.src',
 'scc_pyteam.cookiecutter_templates.fastapi_template.{{cookiecutter.project_name}}.src.constants',
 'scc_pyteam.cookiecutter_templates.fastapi_template.{{cookiecutter.project_name}}.src.dbs',
 'scc_pyteam.cookiecutter_templates.fastapi_template.{{cookiecutter.project_name}}.src.dbs.mongodb',
 'scc_pyteam.cookiecutter_templates.fastapi_template.{{cookiecutter.project_name}}.src.dbs.redis_cache',
 'scc_pyteam.cookiecutter_templates.fastapi_template.{{cookiecutter.project_name}}.src.events',
 'scc_pyteam.cookiecutter_templates.fastapi_template.{{cookiecutter.project_name}}.src.exc_handlers',
 'scc_pyteam.cookiecutter_templates.fastapi_template.{{cookiecutter.project_name}}.src.exceptions',
 'scc_pyteam.cookiecutter_templates.fastapi_template.{{cookiecutter.project_name}}.src.middlewares',
 'scc_pyteam.cookiecutter_templates.fastapi_template.{{cookiecutter.project_name}}.src.models',
 'scc_pyteam.cookiecutter_templates.fastapi_template.{{cookiecutter.project_name}}.src.routers',
 'scc_pyteam.cookiecutter_templates.fastapi_template.{{cookiecutter.project_name}}.src.routers.example',
 'scc_pyteam.cookiecutter_templates.fastapi_template.{{cookiecutter.project_name}}.src.routers.example.schema',
 'scc_pyteam.cookiecutter_templates.fastapi_template.{{cookiecutter.project_name}}.src.routers.example.utils',
 'scc_pyteam.cookiecutter_templates.fastapi_template.{{cookiecutter.project_name}}.src.schemas',
 'scc_pyteam.cookiecutter_templates.fastapi_template.{{cookiecutter.project_name}}.src.settings',
 'scc_pyteam.cookiecutter_templates.fastapi_template.{{cookiecutter.project_name}}.src.settings.teamplates',
 'scc_pyteam.cookiecutter_templates.fastapi_template.{{cookiecutter.project_name}}.src.utils',
 'scc_pyteam.cookiecutter_templates.fastapi_template.{{cookiecutter.project_name}}.src.ws_events',
 'scc_pyteam.cookiecutter_templates.fastapi_template.{{cookiecutter.project_name}}.tests',
 'scc_pyteam.cookiecutter_templates.monorepo_django_fastapi_template',
 'scc_pyteam.cookiecutter_templates.monorepo_django_template',
 'scc_pyteam.cookiecutter_templates.monorepo_fastapi_template']

package_data = \
{'': ['*'],
 'scc_pyteam.cookiecutter_templates.django_template.{{cookiecutter.project_name}}': ['.vscode/*',
                                                                                     'data/postgres/*',
                                                                                     'data/redis/*',
                                                                                     'docs/*',
                                                                                     'envs/*',
                                                                                     'static/*'],
 'scc_pyteam.cookiecutter_templates.django_template.{{cookiecutter.project_name}}.src': ['staticfiles/*'],
 'scc_pyteam.cookiecutter_templates.fastapi_template.{{cookiecutter.project_name}}': ['.vscode/*',
                                                                                      'data/mongo/*',
                                                                                      'data/redis/*',
                                                                                      'docs/*',
                                                                                      'envs/*',
                                                                                      'static/*'],
 'scc_pyteam.cookiecutter_templates.monorepo_django_fastapi_template': ['{{cookiecutter.project_name}}/*'],
 'scc_pyteam.cookiecutter_templates.monorepo_django_template': ['{{cookiecutter.project_name}}/*'],
 'scc_pyteam.cookiecutter_templates.monorepo_fastapi_template': ['{{cookiecutter.project_name}}/*']}

install_requires = \
['bump2version>=1.0.1,<2.0.0',
 'celery>=5.2.7,<6.0.0',
 'cookiecutter>=2.1.1,<3.0.0',
 'django>=4.2,<5.0',
 'djangorestframework>=3.14.0,<4.0.0',
 'fastapi>=0.95.1,<0.96.0',
 'mkdocs-autorefs>=0.4.1,<0.5.0',
 'mkdocs-glightbox>=0.3.2,<0.4.0',
 'mkdocs-material>=9.1.6,<10.0.0',
 'mkdocs-monorepo-plugin>=1.0.4,<2.0.0',
 'mkdocs>=1.4.2,<2.0.0',
 'mkdocstrings>=0.21.2,<0.22.0',
 'mypy>=1.2.0,<2.0.0',
 'pre-commit>=3.2.2,<4.0.0',
 'psutil>=5.9.4,<6.0.0',
 'pydantic[dotenv]>=1.10.7,<2.0.0',
 'pylint[spelling]>=2.17.2,<3.0.0',
 'pytest-asyncio>=0.21.0,<0.22.0',
 'pytest>=7.3.1,<8.0.0',
 'uvloop>=0.17.0,<0.18.0']

entry_points = \
{'console_scripts': ['create-django-app = cocatools:create_django_app',
                     'create-fastapi-app = cocatools:create_fastapi_app',
                     'welcome = cocatools:welcome']}

setup_kwargs = {
    'name': 'scc-pyteam-template-tools',
    'version': '0.2.4',
    'description': '',
    'long_description': '# Installation\n- Require python >= 3.10\n- using pip\n    ```\n    $ pip install coca-tools\n    ```\n- using poetry\n    ```\n    $ poetry add coca-tools\n    ```\n\n\n# Guide\n- Require: using in global environment\n- create fastapi template with command then fill the questions\n    ```\n    $ create-fastapi-app\n    ```\n- create django template with command then fill the questions\n    ```\n    $ create-django-app\n    ```\n',
    'author': 'NhanDD',
    'author_email': 'hp.duongducnhan@gmail.com',
    'maintainer': 'None',
    'maintainer_email': 'None',
    'url': 'None',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'entry_points': entry_points,
    'python_requires': '>=3.10,<4.0',
}


setup(**setup_kwargs)
