
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang.annotation
import typing



class ConstraintConfiguration(java.lang.annotation.Annotation):
    def constraintPackage(self) -> str: ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class ConstraintConfigurationProvider(java.lang.annotation.Annotation):
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...

class ConstraintWeight(java.lang.annotation.Annotation):
    def constraintPackage(self) -> str: ...
    def equals(self, object: typing.Any) -> bool: ...
    def hashCode(self) -> int: ...
    def toString(self) -> str: ...
    def value(self) -> str: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("org.optaplanner.core.api.domain.constraintweight")``.

    ConstraintConfiguration: typing.Type[ConstraintConfiguration]
    ConstraintConfigurationProvider: typing.Type[ConstraintConfigurationProvider]
    ConstraintWeight: typing.Type[ConstraintWeight]
