# Generated by Django 3.2 on 2023-04-24 09:35
from pkg_resources import parse_version
from wagtail import __version__ as WAGTAIL_VERSION

from django.db import migrations
if parse_version(WAGTAIL_VERSION) < parse_version('3.0'):
    from wagtail.core.fields import RichTextField
else:
    from wagtail.fields import RichTextField


class Migration(migrations.Migration):

    dependencies = [
        ('build_test', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=RichTextField(default=''),
        ),
    ]
