VERSION_YEAR = 2023
VERSION_MONTH = int('04')
VERSION_DAY = int('29')
VERSION_HOUR = int('06')
VERSION_MINUTE = int('50')
MAJOR_VERSION = 0
MINOR_VERSION = 3
PATCH_VERSION = 202304290650
version_date = '2023/04/29 06:50'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
