
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-30T15:24:33+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "32d8cb70e6ab02d134a2cd0973257067f8f23688",
 "version": "1.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
