
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-26T18:13:54+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "4569e1e5b5a8adaad63d1518cd4eb1226e73e907",
 "version": "1.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
