
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-16T08:02:22-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "71c068458390192a4753e7127ba9c244eec59697",
 "version": "2023.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
