# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations

import json
import pprint
import re  # noqa: F401

from pydantic import BaseModel, Field, StrictStr


class EftNumber(BaseModel):
    """
    EftNumber
    """

    account_number: StrictStr = Field(..., description="The account number.")
    institution_number: StrictStr = Field(..., description="The institution number.")
    branch_number: StrictStr = Field(..., description="The branch number.")
    __properties = ["account_number", "institution_number", "branch_number"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> EftNumber:
        """Create an instance of EftNumber from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> EftNumber:
        """Create an instance of EftNumber from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return EftNumber.parse_obj(obj)

        _obj = EftNumber.parse_obj(
            {
                "account_number": obj.get("account_number"),
                "institution_number": obj.get("institution_number"),
                "branch_number": obj.get("branch_number"),
            }
        )
        return _obj
