
import sys
if sys.version_info >= (3, 8):
    from typing import Protocol
else:
    from typing_extensions import Protocol

import java.lang
import org.kie.api.runtime.rule
import org.optaplanner.core.api.score
import org.optaplanner.core.api.score.holder
import typing



class SimpleScore(org.optaplanner.core.api.score.Score['SimpleScore']):
    ZERO: typing.ClassVar['SimpleScore'] = ...
    ONE: typing.ClassVar['SimpleScore'] = ...
    def abs(self) -> 'SimpleScore': ...
    def add(self, simpleScore: 'SimpleScore') -> 'SimpleScore': ...
    def compareTo(self, simpleScore: 'SimpleScore') -> int: ...
    def divide(self, double: float) -> 'SimpleScore': ...
    def equals(self, object: typing.Any) -> bool: ...
    def getScore(self) -> int: ...
    def hashCode(self) -> int: ...
    def initScore(self) -> int: ...
    def isFeasible(self) -> bool: ...
    def multiply(self, double: float) -> 'SimpleScore': ...
    @staticmethod
    def of(int: int) -> 'SimpleScore': ...
    @staticmethod
    def ofUninitialized(int: int, int2: int) -> 'SimpleScore': ...
    @staticmethod
    def parseScore(string: str) -> 'SimpleScore': ...
    def power(self, double: float) -> 'SimpleScore': ...
    def score(self) -> int: ...
    def subtract(self, simpleScore: 'SimpleScore') -> 'SimpleScore': ...
    def toLevelNumbers(self) -> typing.MutableSequence[java.lang.Number]: ...
    def toShortString(self) -> str: ...
    def toString(self) -> str: ...
    def withInitScore(self, int: int) -> 'SimpleScore': ...
    def zero(self) -> 'SimpleScore': ...

class SimpleScoreHolder(org.optaplanner.core.api.score.holder.ScoreHolder[SimpleScore]):
    def addConstraintMatch(self, ruleContext: org.kie.api.runtime.rule.RuleContext, int: int) -> None: ...
    def impactScore(self, ruleContext: org.kie.api.runtime.rule.RuleContext, int: int) -> None: ...
    @typing.overload
    def penalize(self, ruleContext: org.kie.api.runtime.rule.RuleContext, int: int) -> None: ...
    @typing.overload
    def penalize(self, ruleContext: org.kie.api.runtime.rule.RuleContext) -> None: ...
    @typing.overload
    def reward(self, ruleContext: org.kie.api.runtime.rule.RuleContext, int: int) -> None: ...
    @typing.overload
    def reward(self, ruleContext: org.kie.api.runtime.rule.RuleContext) -> None: ...


class __module_protocol__(Protocol):
    # A module protocol which reflects the result of ``jp.JPackage("org.optaplanner.core.api.score.buildin.simple")``.

    SimpleScore: typing.Type[SimpleScore]
    SimpleScoreHolder: typing.Type[SimpleScoreHolder]
