# Generated by Django 3.2 on 2023-02-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_log_hashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='device',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
