# Generated by Django 3.2 on 2023-02-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20230223_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='isp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
