
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-25T16:05:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "4a9e737382596056a232ffb18c49faba621ec7c0",
 "version": "23.04.00"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
