# (generated with --quick)

import hsuanwu.xplore.distribution.base
import torch as th
from torch import distributions as pyd
from typing import Annotated, Any, Type

BaseDistribution: Type[hsuanwu.xplore.distribution.base.BaseDistribution]

class DiagonalGaussian(hsuanwu.xplore.distribution.base.BaseDistribution):
    __doc__: str
    _mu: Any
    _sigma: Any
    dist: Any
    mean: Annotated[Any, 'property']
    def __init__(self, mu, sigma) -> None: ...
    def entropy(self) -> Any: ...
    def log_prob(self, actions) -> Any: ...
    def mode(self) -> Any: ...
    def reset(self) -> None: ...
    def rsample(self, sample_shape = ...) -> Any: ...
    def sample(self, sample_shape = ...) -> Any: ...
