
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-25T16:01:11-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a00df71b5edd2a2894c99ad38363eb21d46e0ebf",
 "version": "23.04.00"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
