
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-28T08:11:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b39f6b492544a23b2fb2b180fb7a425271dc8afb",
 "version": "0.3.0.post0.dev13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
