ALLOWED_TAGS = [
    "font",
    "del",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "blockquote",
    "p",
    "a",
    "ul",
    "ol",
    "sup",
    "sub",
    "nl",
    "li",
    "b",
    "i",
    "u",
    "strong",
    "em",
    "strike",
    "code",
    "hr",
    "br",
    "div",
    "table",
    "thead",
    "caption",
    "tbody",
    "tr",
    "th",
    "td",
    "pre",
    "span",
    "img",
]

ALLOWED_ATTRIBUTES = {
    "font": ["color", "data-mx-bg-color", "data-mx-color", "style"],
    "span": ["data-mx-bg-color", "data-mx-color", "style"],
    "a": ["href", "name", "target", "rel"],
    "img": ["src", "width", "height", "alt", "title"],
    "ol": ["start"],
}
