
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-27T08:46:25+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "47dd25f1f63bcb869c75d0e8c436aceee34d0496",
 "version": "0.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
