# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from common_pb2 import (
    EntityTypeValue as common_pb2___EntityTypeValue,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from google.protobuf.timestamp_pb2 import (
    Timestamp as google___protobuf___timestamp_pb2___Timestamp,
)

from integration_source_pb2 import (
    IntegrationSourceValue as integration_source_pb2___IntegrationSourceValue,
)

from typing import (
    Iterable as typing___Iterable,
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

AudienceSyncSyncStateValue = typing___NewType('AudienceSyncSyncStateValue', builtin___int)
type___AudienceSyncSyncStateValue = AudienceSyncSyncStateValue
AudienceSyncSyncState: _AudienceSyncSyncState
class _AudienceSyncSyncState(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[AudienceSyncSyncStateValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    AUDIENCE_SYNC_SYNC_STATE_UNSPECIFIED = typing___cast(AudienceSyncSyncStateValue, 0)
    AUDIENCE_SYNC_SYNC_IDLE = typing___cast(AudienceSyncSyncStateValue, 1)
    AUDIENCE_SYNC_SYNC_SCHEDULED = typing___cast(AudienceSyncSyncStateValue, 2)
    AUDIENCE_SYNC_SYNC_IN_PROGRESS = typing___cast(AudienceSyncSyncStateValue, 3)
AUDIENCE_SYNC_SYNC_STATE_UNSPECIFIED = typing___cast(AudienceSyncSyncStateValue, 0)
AUDIENCE_SYNC_SYNC_IDLE = typing___cast(AudienceSyncSyncStateValue, 1)
AUDIENCE_SYNC_SYNC_SCHEDULED = typing___cast(AudienceSyncSyncStateValue, 2)
AUDIENCE_SYNC_SYNC_IN_PROGRESS = typing___cast(AudienceSyncSyncStateValue, 3)
type___AudienceSyncSyncState = AudienceSyncSyncState

AudienceSyncStateValue = typing___NewType('AudienceSyncStateValue', builtin___int)
type___AudienceSyncStateValue = AudienceSyncStateValue
AudienceSyncState: _AudienceSyncState
class _AudienceSyncState(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[AudienceSyncStateValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    AUDIENCE_SYNC_STATE_UNSPECIFIED = typing___cast(AudienceSyncStateValue, 0)
    AUDIENCE_SYNC_ENABLED = typing___cast(AudienceSyncStateValue, 1)
    AUDIENCE_SYNC_PAUSED = typing___cast(AudienceSyncStateValue, 2)
AUDIENCE_SYNC_STATE_UNSPECIFIED = typing___cast(AudienceSyncStateValue, 0)
AUDIENCE_SYNC_ENABLED = typing___cast(AudienceSyncStateValue, 1)
AUDIENCE_SYNC_PAUSED = typing___cast(AudienceSyncStateValue, 2)
type___AudienceSyncState = AudienceSyncState

AudienceSyncScheduleValue = typing___NewType('AudienceSyncScheduleValue', builtin___int)
type___AudienceSyncScheduleValue = AudienceSyncScheduleValue
AudienceSyncSchedule: _AudienceSyncSchedule
class _AudienceSyncSchedule(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[AudienceSyncScheduleValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    AUDIENCE_SYNC_SCHEDULE_UNSPECIFIED = typing___cast(AudienceSyncScheduleValue, 0)
    AUDIENCE_SYNC_SCHEDULE_DAILY = typing___cast(AudienceSyncScheduleValue, 1)
AUDIENCE_SYNC_SCHEDULE_UNSPECIFIED = typing___cast(AudienceSyncScheduleValue, 0)
AUDIENCE_SYNC_SCHEDULE_DAILY = typing___cast(AudienceSyncScheduleValue, 1)
type___AudienceSyncSchedule = AudienceSyncSchedule

AudienceSyncLogStateValue = typing___NewType('AudienceSyncLogStateValue', builtin___int)
type___AudienceSyncLogStateValue = AudienceSyncLogStateValue
AudienceSyncLogState: _AudienceSyncLogState
class _AudienceSyncLogState(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[AudienceSyncLogStateValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    AUDIENCE_SYNC_LOG_STATE_UNSPECIFIED = typing___cast(AudienceSyncLogStateValue, 0)
    AUDIENCE_SYNC_LOG_STATE_IN_PROGRESS = typing___cast(AudienceSyncLogStateValue, 1)
    AUDIENCE_SYNC_LOG_STATE_SUCCESS = typing___cast(AudienceSyncLogStateValue, 2)
    AUDIENCE_SYNC_LOG_STATE_FAILED = typing___cast(AudienceSyncLogStateValue, 3)
AUDIENCE_SYNC_LOG_STATE_UNSPECIFIED = typing___cast(AudienceSyncLogStateValue, 0)
AUDIENCE_SYNC_LOG_STATE_IN_PROGRESS = typing___cast(AudienceSyncLogStateValue, 1)
AUDIENCE_SYNC_LOG_STATE_SUCCESS = typing___cast(AudienceSyncLogStateValue, 2)
AUDIENCE_SYNC_LOG_STATE_FAILED = typing___cast(AudienceSyncLogStateValue, 3)
type___AudienceSyncLogState = AudienceSyncLogState

class SyncField(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    internal_field: typing___Text = ...
    external_field: typing___Text = ...

    def __init__(self,
        *,
        internal_field : typing___Optional[typing___Text] = None,
        external_field : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"field",b"field",u"internal_field",b"internal_field"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"external_field",b"external_field",u"field",b"field",u"internal_field",b"internal_field"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"field",b"field"]) -> typing_extensions___Literal["internal_field"]: ...
type___SyncField = SyncField

class SalesforceContactSync(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    entity_type: common_pb2___EntityTypeValue = ...
    sync_batch_limit: builtin___int = ...

    @property
    def mappings(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___SyncField]: ...

    def __init__(self,
        *,
        entity_type : typing___Optional[common_pb2___EntityTypeValue] = None,
        mappings : typing___Optional[typing___Iterable[type___SyncField]] = None,
        sync_batch_limit : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"entity_type",b"entity_type",u"mappings",b"mappings",u"sync_batch_limit",b"sync_batch_limit"]) -> None: ...
type___SalesforceContactSync = SalesforceContactSync

class AudienceDestinationConfig(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    destination: integration_source_pb2___IntegrationSourceValue = ...

    @property
    def salesforce_contact_sync(self) -> type___SalesforceContactSync: ...

    def __init__(self,
        *,
        destination : typing___Optional[integration_source_pb2___IntegrationSourceValue] = None,
        salesforce_contact_sync : typing___Optional[type___SalesforceContactSync] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"salesforce_contact_sync",b"salesforce_contact_sync",u"sync",b"sync"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"destination",b"destination",u"salesforce_contact_sync",b"salesforce_contact_sync",u"sync",b"sync"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"sync",b"sync"]) -> typing_extensions___Literal["salesforce_contact_sync"]: ...
type___AudienceDestinationConfig = AudienceDestinationConfig

class AudienceSync(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    organization_id: typing___Text = ...
    audience_id: typing___Text = ...
    audience_sync_id: typing___Text = ...
    sync_schedule: type___AudienceSyncScheduleValue = ...
    sync_state: type___AudienceSyncSyncStateValue = ...
    state: type___AudienceSyncStateValue = ...

    @property
    def config(self) -> type___AudienceDestinationConfig: ...

    @property
    def last_synced_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def next_sync_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def created_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def updated_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def deleted_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    def __init__(self,
        *,
        organization_id : typing___Optional[typing___Text] = None,
        audience_id : typing___Optional[typing___Text] = None,
        audience_sync_id : typing___Optional[typing___Text] = None,
        sync_schedule : typing___Optional[type___AudienceSyncScheduleValue] = None,
        sync_state : typing___Optional[type___AudienceSyncSyncStateValue] = None,
        state : typing___Optional[type___AudienceSyncStateValue] = None,
        config : typing___Optional[type___AudienceDestinationConfig] = None,
        last_synced_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        next_sync_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        created_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        updated_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        deleted_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"config",b"config",u"created_at",b"created_at",u"deleted_at",b"deleted_at",u"last_synced_at",b"last_synced_at",u"next_sync_at",b"next_sync_at",u"updated_at",b"updated_at"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"audience_id",b"audience_id",u"audience_sync_id",b"audience_sync_id",u"config",b"config",u"created_at",b"created_at",u"deleted_at",b"deleted_at",u"last_synced_at",b"last_synced_at",u"next_sync_at",b"next_sync_at",u"organization_id",b"organization_id",u"state",b"state",u"sync_schedule",b"sync_schedule",u"sync_state",b"sync_state",u"updated_at",b"updated_at"]) -> None: ...
type___AudienceSync = AudienceSync

class LinkedInAdsSyncLogMetadata(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    users_added_to_campaign_count: builtin___int = ...
    users_removed_from_campaign_count: builtin___int = ...

    def __init__(self,
        *,
        users_added_to_campaign_count : typing___Optional[builtin___int] = None,
        users_removed_from_campaign_count : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"users_added_to_campaign_count",b"users_added_to_campaign_count",u"users_removed_from_campaign_count",b"users_removed_from_campaign_count"]) -> None: ...
type___LinkedInAdsSyncLogMetadata = LinkedInAdsSyncLogMetadata

class SalesforceSyncLogMetadata(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    contacts_synced_count: builtin___int = ...

    def __init__(self,
        *,
        contacts_synced_count : typing___Optional[builtin___int] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"contacts_synced_count",b"contacts_synced_count"]) -> None: ...
type___SalesforceSyncLogMetadata = SalesforceSyncLogMetadata

class AudienceSyncLogMetadata(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def linked_in_ads_sync_log_metadata(self) -> type___LinkedInAdsSyncLogMetadata: ...

    @property
    def salesforce_sync_log_metadata(self) -> type___SalesforceSyncLogMetadata: ...

    def __init__(self,
        *,
        linked_in_ads_sync_log_metadata : typing___Optional[type___LinkedInAdsSyncLogMetadata] = None,
        salesforce_sync_log_metadata : typing___Optional[type___SalesforceSyncLogMetadata] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"linked_in_ads_sync_log_metadata",b"linked_in_ads_sync_log_metadata",u"metadata",b"metadata",u"salesforce_sync_log_metadata",b"salesforce_sync_log_metadata"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"linked_in_ads_sync_log_metadata",b"linked_in_ads_sync_log_metadata",u"metadata",b"metadata",u"salesforce_sync_log_metadata",b"salesforce_sync_log_metadata"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"metadata",b"metadata"]) -> typing_extensions___Literal["linked_in_ads_sync_log_metadata","salesforce_sync_log_metadata"]: ...
type___AudienceSyncLogMetadata = AudienceSyncLogMetadata

class AudienceSyncLog(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    organization_id: typing___Text = ...
    audience_sync_id: typing___Text = ...
    audience_sync_log_id: typing___Text = ...
    state: type___AudienceSyncLogStateValue = ...

    @property
    def metadata(self) -> type___AudienceSyncLogMetadata: ...

    @property
    def created_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def updated_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def completed_at(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    def __init__(self,
        *,
        organization_id : typing___Optional[typing___Text] = None,
        audience_sync_id : typing___Optional[typing___Text] = None,
        audience_sync_log_id : typing___Optional[typing___Text] = None,
        state : typing___Optional[type___AudienceSyncLogStateValue] = None,
        metadata : typing___Optional[type___AudienceSyncLogMetadata] = None,
        created_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        updated_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        completed_at : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"completed_at",b"completed_at",u"created_at",b"created_at",u"metadata",b"metadata",u"updated_at",b"updated_at"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"audience_sync_id",b"audience_sync_id",u"audience_sync_log_id",b"audience_sync_log_id",u"completed_at",b"completed_at",u"created_at",b"created_at",u"metadata",b"metadata",u"organization_id",b"organization_id",u"state",b"state",u"updated_at",b"updated_at"]) -> None: ...
type___AudienceSyncLog = AudienceSyncLog
