
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-27T11:32:43-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ee2b884f57dee1cf13f9201aa2f80698d08f3f64",
 "version": "v1.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
