
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-27T00:42:07+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3c7ffc3939075a307188bc4c43d330386aeb6b45",
 "version": "2.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
