
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-26T14:20:02-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b3af6222e8c9f822d5b6e3de7c2b05b7cdc92134",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
