# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import re  # noqa: F401

from aenum import Enum


class LinkError(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    SYSTEM_ERROR = "system_error"
    PROVIDER_ERROR = "provider_error"
    INSTITUTION_ERROR = "institution_error"
    USER_ERROR = "user_error"
    AUTH_EXPIRED = "auth_expired"
    INCOMPLETE = "incomplete"
    PAYMENT_ERROR = "payment_error"
