# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations

import json
import pprint
import re  # noqa: F401

from pydantic import BaseModel, Field, StrictStr

from moneykit.models.link import Link


class ExchangeTokenResponse(BaseModel):
    """
    ExchangeTokenResponse
    """

    link_id: StrictStr = Field(..., description="The unique ID associated with this link.")
    link: Link = ...
    __properties = ["link_id", "link"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ExchangeTokenResponse:
        """Create an instance of ExchangeTokenResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of link
        if self.link:
            _dict["link"] = self.link.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ExchangeTokenResponse:
        """Create an instance of ExchangeTokenResponse from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return ExchangeTokenResponse.parse_obj(obj)

        _obj = ExchangeTokenResponse.parse_obj(
            {
                "link_id": obj.get("link_id"),
                "link": Link.from_dict(obj.get("link")) if obj.get("link") is not None else None,
            }
        )
        return _obj
