
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-28T17:02:27+0530",
 "dirty": true,
 "error": null,
 "full-revisionid": "a95f7a765f2338268c2e98a4e9e49446cf85600a",
 "version": "23.07.00a+25.ga95f7a7.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
