#ifndef MYPYC_NATIVE_INTERNAL_H
#define MYPYC_NATIVE_INTERNAL_H
#include <Python.h>
#include <CPy.h>
#include "__native.h"

int CPyGlobalsInit(void);

extern PyObject *CPyStatics[68];
extern const char * const CPyLit_Str[];
extern const char * const CPyLit_Bytes[];
extern const char * const CPyLit_Int[];
extern const double CPyLit_Float[];
extern const double CPyLit_Complex[];
extern const int CPyLit_Tuple[];
extern const int CPyLit_FrozenSet[];
extern CPyModule *CPyModule_asgi_context_internal;
extern CPyModule *CPyModule_asgi_context;
extern PyObject *CPyStatic_globals;
extern CPyModule *CPyModule_builtins_internal;
extern CPyModule *CPyModule_builtins;
extern CPyModule *CPyModule_abc_internal;
extern CPyModule *CPyModule_abc;
extern CPyModule *CPyModule_collections_internal;
extern CPyModule *CPyModule_collections;
extern CPyModule *CPyModule_collections___abc_internal;
extern CPyModule *CPyModule_collections___abc;
extern CPyModule *CPyModule_contextlib_internal;
extern CPyModule *CPyModule_contextlib;
extern CPyModule *CPyModule_contextvars_internal;
extern CPyModule *CPyModule_contextvars;
extern CPyModule *CPyModule_functools_internal;
extern CPyModule *CPyModule_functools;
extern CPyModule *CPyModule_typing_internal;
extern CPyModule *CPyModule_typing;
extern PyTypeObject *CPyType_RequestContextException;
extern PyTypeObject *CPyType_HeaderValidationException;
extern PyTypeObject *CPyType_Context;
extern PyObject *CPyDef_Context(void);
extern PyTypeObject *CPyType_ContextMiddleware;
extern PyObject *CPyDef_ContextMiddleware(PyObject *cpy_r_app);
extern PyTypeObject *CPyType_AbstractHeadersExtractorMiddleware;
extern PyObject *CPyDef_AbstractHeadersExtractorMiddleware(PyObject *cpy_r_app);
extern PyTypeObject *CPyType_HeadersExtractorMiddlewareFactory;
extern PyObject *CPyDef_HeadersExtractorMiddlewareFactory(void);
extern PyTypeObject *CPyType_new_context_env;
extern PyObject *CPyDef_new_context_env(void);
extern PyTypeObject *CPyType_new_context_gen;
extern PyObject *CPyDef_new_context_gen(void);
extern PyTypeObject *CPyType___call___3_ContextMiddleware_env;
extern PyObject *CPyDef___call___3_ContextMiddleware_env(void);
extern PyTypeObject *CPyType___call___3_ContextMiddleware_gen;
extern PyObject *CPyDef___call___3_ContextMiddleware_gen(void);
extern PyTypeObject *CPyType___call___3_AbstractHeadersExtractorMiddleware_env;
extern PyObject *CPyDef___call___3_AbstractHeadersExtractorMiddleware_env(void);
extern PyTypeObject *CPyType___call___3_AbstractHeadersExtractorMiddleware_gen;
extern PyObject *CPyDef___call___3_AbstractHeadersExtractorMiddleware_gen(void);
extern PyTypeObject *CPyType_build_HeadersExtractorMiddlewareFactory_env;
extern PyObject *CPyDef_build_HeadersExtractorMiddlewareFactory_env(void);
extern PyTypeObject *CPyType___mypyc_lambda__0_build_HeadersExtractorMiddlewareFactory_obj;
extern PyObject *CPyDef___mypyc_lambda__0_build_HeadersExtractorMiddlewareFactory_obj(void);
extern PyTypeObject *CPyType___mypyc_lambda__1_build_HeadersExtractorMiddlewareFactory_obj;
extern PyObject *CPyDef___mypyc_lambda__1_build_HeadersExtractorMiddlewareFactory_obj(void);
extern char CPyDef_Context_____init__(PyObject *cpy_r_self);
extern PyObject *CPyPy_Context_____init__(PyObject *self, PyObject *args, PyObject *kw);
extern PyObject *CPyDef_Context___data(PyObject *cpy_r_self);
extern PyObject *CPyPy_Context___data(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_new_context_gen_____mypyc_generator_helper__(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_type, PyObject *cpy_r_value, PyObject *cpy_r_traceback, PyObject *cpy_r_arg);
extern PyObject *CPyPy_new_context_gen_____mypyc_generator_helper__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_new_context_gen_____next__(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy_new_context_gen_____next__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_new_context_gen___send(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_arg);
extern PyObject *CPyPy_new_context_gen___send(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_new_context_gen_____iter__(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy_new_context_gen_____iter__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_new_context_gen___throw(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_type, PyObject *cpy_r_value, PyObject *cpy_r_traceback);
extern PyObject *CPyPy_new_context_gen___throw(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_new_context_gen___close(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy_new_context_gen___close(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_new_context(void);
extern PyObject *CPyPy_new_context(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern char CPyDef_ContextMiddleware_____init__(PyObject *cpy_r_self, PyObject *cpy_r_app);
extern PyObject *CPyPy_ContextMiddleware_____init__(PyObject *self, PyObject *args, PyObject *kw);
extern PyObject *CPyDef___call___3_ContextMiddleware_gen_____mypyc_generator_helper__(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_type, PyObject *cpy_r_value, PyObject *cpy_r_traceback, PyObject *cpy_r_arg);
extern PyObject *CPyPy___call___3_ContextMiddleware_gen_____mypyc_generator_helper__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef___call___3_ContextMiddleware_gen_____next__(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy___call___3_ContextMiddleware_gen_____next__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef___call___3_ContextMiddleware_gen___send(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_arg);
extern PyObject *CPyPy___call___3_ContextMiddleware_gen___send(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef___call___3_ContextMiddleware_gen_____iter__(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy___call___3_ContextMiddleware_gen_____iter__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef___call___3_ContextMiddleware_gen___throw(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_type, PyObject *cpy_r_value, PyObject *cpy_r_traceback);
extern PyObject *CPyPy___call___3_ContextMiddleware_gen___throw(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef___call___3_ContextMiddleware_gen___close(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy___call___3_ContextMiddleware_gen___close(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef___call___3_ContextMiddleware_gen_____await__(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy___call___3_ContextMiddleware_gen_____await__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_ContextMiddleware_____call__(PyObject *cpy_r_self, PyObject *cpy_r_scope, PyObject *cpy_r_receive, PyObject *cpy_r_send);
extern PyObject *CPyPy_ContextMiddleware_____call__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern char CPyDef_AbstractHeadersExtractorMiddleware_____init__(PyObject *cpy_r_self, PyObject *cpy_r_app);
extern PyObject *CPyPy_AbstractHeadersExtractorMiddleware_____init__(PyObject *self, PyObject *args, PyObject *kw);
extern PyObject *CPyDef_AbstractHeadersExtractorMiddleware___header_names(PyObject *cpy_r_self);
extern PyObject *CPyPy_AbstractHeadersExtractorMiddleware___header_names(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_AbstractHeadersExtractorMiddleware___validators(PyObject *cpy_r_self);
extern PyObject *CPyPy_AbstractHeadersExtractorMiddleware___validators(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef___call___3_AbstractHeadersExtractorMiddleware_gen_____mypyc_generator_helper__(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_type, PyObject *cpy_r_value, PyObject *cpy_r_traceback, PyObject *cpy_r_arg);
extern PyObject *CPyPy___call___3_AbstractHeadersExtractorMiddleware_gen_____mypyc_generator_helper__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef___call___3_AbstractHeadersExtractorMiddleware_gen_____next__(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy___call___3_AbstractHeadersExtractorMiddleware_gen_____next__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef___call___3_AbstractHeadersExtractorMiddleware_gen___send(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_arg);
extern PyObject *CPyPy___call___3_AbstractHeadersExtractorMiddleware_gen___send(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef___call___3_AbstractHeadersExtractorMiddleware_gen_____iter__(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy___call___3_AbstractHeadersExtractorMiddleware_gen_____iter__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef___call___3_AbstractHeadersExtractorMiddleware_gen___throw(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_type, PyObject *cpy_r_value, PyObject *cpy_r_traceback);
extern PyObject *CPyPy___call___3_AbstractHeadersExtractorMiddleware_gen___throw(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef___call___3_AbstractHeadersExtractorMiddleware_gen___close(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy___call___3_AbstractHeadersExtractorMiddleware_gen___close(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef___call___3_AbstractHeadersExtractorMiddleware_gen_____await__(PyObject *cpy_r___mypyc_self__);
extern PyObject *CPyPy___call___3_AbstractHeadersExtractorMiddleware_gen_____await__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_AbstractHeadersExtractorMiddleware_____call__(PyObject *cpy_r_self, PyObject *cpy_r_scope, PyObject *cpy_r_receive, PyObject *cpy_r_send);
extern PyObject *CPyPy_AbstractHeadersExtractorMiddleware_____call__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef___mypyc_lambda__0_build_HeadersExtractorMiddlewareFactory_obj_____get__(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_instance, PyObject *cpy_r_owner);
extern PyObject *CPyPy___mypyc_lambda__0_build_HeadersExtractorMiddlewareFactory_obj_____get__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef___mypyc_lambda__0_build_HeadersExtractorMiddlewareFactory_obj_____call__(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_self);
extern PyObject *CPyPy___mypyc_lambda__0_build_HeadersExtractorMiddlewareFactory_obj_____call__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef___mypyc_lambda__1_build_HeadersExtractorMiddlewareFactory_obj_____get__(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_instance, PyObject *cpy_r_owner);
extern PyObject *CPyPy___mypyc_lambda__1_build_HeadersExtractorMiddlewareFactory_obj_____get__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef___mypyc_lambda__1_build_HeadersExtractorMiddlewareFactory_obj_____call__(PyObject *cpy_r___mypyc_self__, PyObject *cpy_r_self);
extern PyObject *CPyPy___mypyc_lambda__1_build_HeadersExtractorMiddlewareFactory_obj_____call__(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern PyObject *CPyDef_HeadersExtractorMiddlewareFactory___build(PyObject *cpy_r_base_name, PyObject *cpy_r_header_names, PyObject *cpy_r_validators);
extern PyObject *CPyPy_HeadersExtractorMiddlewareFactory___build(PyObject *self, PyObject *const *args, size_t nargs, PyObject *kwnames);
extern char CPyDef___top_level__(void);
#endif
