from enum import Enum


class ClusterStatusType(str, Enum):
    CRDB_CLUSTER_DISRUPTION_FAILED = "CRDB_CLUSTER_DISRUPTION_FAILED"
    CRDB_CLUSTER_DISRUPTION_RUNNING = "CRDB_CLUSTER_DISRUPTION_RUNNING"
    CRDB_CMEK_OPERATION_FAILED = "CRDB_CMEK_OPERATION_FAILED"
    CRDB_CMEK_OPERATION_RUNNING = "CRDB_CMEK_OPERATION_RUNNING"
    CRDB_CUSTOM_CLIENT_CA_FAILED = "CRDB_CUSTOM_CLIENT_CA_FAILED"
    CRDB_CUSTOM_CLIENT_CA_RUNNING = "CRDB_CUSTOM_CLIENT_CA_RUNNING"
    CRDB_EDIT_CLUSTER_FAILED = "CRDB_EDIT_CLUSTER_FAILED"
    CRDB_EDIT_CLUSTER_RUNNING = "CRDB_EDIT_CLUSTER_RUNNING"
    CRDB_INSTANCE_UPDATE_FAILED = "CRDB_INSTANCE_UPDATE_FAILED"
    CRDB_INSTANCE_UPDATE_RUNNING = "CRDB_INSTANCE_UPDATE_RUNNING"
    CRDB_LOG_EXPORT_OPERATION_FAILED = "CRDB_LOG_EXPORT_OPERATION_FAILED"
    CRDB_LOG_EXPORT_OPERATION_RUNNING = "CRDB_LOG_EXPORT_OPERATION_RUNNING"
    CRDB_MAJOR_ROLLBACK_FAILED = "CRDB_MAJOR_ROLLBACK_FAILED"
    CRDB_MAJOR_ROLLBACK_RUNNING = "CRDB_MAJOR_ROLLBACK_RUNNING"
    CRDB_MAJOR_UPGRADE_FAILED = "CRDB_MAJOR_UPGRADE_FAILED"
    CRDB_MAJOR_UPGRADE_RUNNING = "CRDB_MAJOR_UPGRADE_RUNNING"
    CRDB_PATCH_FAILED = "CRDB_PATCH_FAILED"
    CRDB_PATCH_RUNNING = "CRDB_PATCH_RUNNING"
    CRDB_REPAVE_FAILED = "CRDB_REPAVE_FAILED"
    CRDB_REPAVE_RUNNING = "CRDB_REPAVE_RUNNING"
    CRDB_SCALE_FAILED = "CRDB_SCALE_FAILED"
    CRDB_SCALE_RUNNING = "CRDB_SCALE_RUNNING"
    MAINTENANCE_RUNNING = "MAINTENANCE_RUNNING"
    TENANT_RESTORE_FAILED = "TENANT_RESTORE_FAILED"
    TENANT_RESTORE_RUNNING = "TENANT_RESTORE_RUNNING"
    UNSPECIFIED = "UNSPECIFIED"

    def __str__(self) -> str:
        return str(self.value)
