import cpp_easygraph as ceg
import igraph as ig
a =ceg.Graph()
a.add_edge(1,2)
a.add_edge(2,3)
a.add_edge(4,5)
a.add_edge(3,5)
b = ig.Graph()
b.add_vertices(6)
b.add_edge(1,2)
b.add_edge(2,3)
b.add_edge(4,5)
b.add_edge(3,5)
print("bet")
print(ceg.cpp_betweenness_centrality(a))
print(b.betweenness(directed=False))
print("clo")
print(ceg.cpp_closeness_centrality(a))
print(b.closeness())
print("dij")
print(ceg.cpp_dijkstra_multisource(a,sources=[1]))
print(b.distances(source=[1]))