
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: envoy.gpg.sign:package

from setuptools import setup

setup(**{
    'author': 'Ryan Northey',
    'author_email': 'ryan@synca.io',
    'description': '"GPG signing util used in Envoy proxy\'s CI"',
    'entry_points': {
        'console_scripts': [
            'envoy.gpg.sign=envoy.gpg.sign:cmd',
        ],
    },
    'install_requires': (
        'aio.run.runner>=0.3.3',
        'envoy.base.utils>=0.4.7',
        'envoy.gpg.identity>=0.1.1',
    ),
    'license': 'Apache Software License 2.0',
    'long_description': """
envoy.gpg.sign
==============

GPG signing util used in Envoy proxy's CI
""",
    'maintainer': 'Ryan Northey',
    'maintainer_email': 'ryan@synca.io',
    'name': 'envoy.gpg.sign',
    'namespace_packages': (
    ),
    'package_data': {
        'envoy.gpg.sign': (
            'py.typed',
        ),
    },
    'packages': (
        'envoy.gpg.sign',
    ),
    'python_requires': '>=3.10.0',
    'url': 'https://github.com/envoyproxy/pytooling/tree/main/envoy.gpg.sign',
    'version': '0.2.0',
})
