# coding: utf-8

"""
    MoneyKit API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, StrictBool


class MoneylinkFeatures(BaseModel):
    """
    Enables optional testing and UI features.
    """

    bug_reporter: Optional[StrictBool] = Field(
        False,
        description="If enabled, the user can perform a gesture that displays a bug reporter directly in the SDK's UI.",
    )
    enable_money_id: Optional[StrictBool] = Field(
        False, description="If enabled, the user can register for, or login into, Money ID."
    )
    __properties = ["bug_reporter", "enable_money_id"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MoneylinkFeatures:
        """Create an instance of MoneylinkFeatures from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MoneylinkFeatures:
        """Create an instance of MoneylinkFeatures from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return MoneylinkFeatures.parse_obj(obj)

        _obj = MoneylinkFeatures.parse_obj(
            {
                "bug_reporter": obj.get("bug_reporter") if obj.get("bug_reporter") is not None else False,
                "enable_money_id": obj.get("enable_money_id") if obj.get("enable_money_id") is not None else False,
            }
        )
        return _obj
