
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-28T16:46:25-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f1db2c59951f3112982a3f2ba33f1fcd5e7c4ee7",
 "version": "0.16.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
