
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-25T13:47:44-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "68a248e35c7f74b46ed6c1d20d34528e3fa1f40e",
 "version": "v0.3.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
