
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-26T16:42:58+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a38b309d7b9dcd89855d2c028d2be783c8310c25",
 "version": "0.1.155"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
